### ISSUE TITLE
Not vertically centred in Firefox

### ISSUE THREAD

**Issue by lumpysimon** [medienbaecker/kirby-autofavicon#2]
The favicons look great in Chrome, but in Firefox the letter is not vertically centred, it's much closer to the top of the circle.

**Chrome:**
<img width="128" alt="Screenshot 2021-02-02 at 21 21 22" src="https://user-images.githubusercontent.com/625372/106664189-a0158300-659c-11eb-88ea-b363b3a666ce.png">

**Firefox:**
<img width="138" alt="Screenshot 2021-02-02 at 21 19 58" src="https://user-images.githubusercontent.com/625372/106664013-6e042100-659c-11eb-9400-429e271dbe30.png">

(very nifty plugin by the way, thank you 👍)

**Comment by medienbaecker** [comment]
Thanks for the nice words!

I actually use the following code to center the text:
```
text-anchor="middle" dominant-baseline="central"
```
Not sure why Firefox doesn't like that.

**Comment by medienbaecker** [comment]
I changed some things around and now it seems to look good in Chrome *and* Firefox.

**Comment by lumpysimon** [comment]
Perfect, thank you :)
