### ISSUE TITLE
Dynamic Colors

### ISSUE THREAD

**Issue by metakolor** [medienbaecker/kirby-autofavicon#3]
Hey,

it would be awesome to use dynamic colors with this.

```
'options' => [
		'color' =>  kirby()->site()->kolor(),
		'color_dark' => kirby()->site()->kolor2(),
		'text' => kirby()->site()->title()->value()[0]
	],
```

This does not work :-/

**Comment by medienbaecker** [comment]
Did you try using `kirby()->site()->kolor()->value()` so it's using the field value?

**Comment by metakolor** [comment]
Yes I've already tried this --> no error but also no favicon. 

```
'options' => [
		'color' => kirby()->site()->kolorNuance()->value(),
		'color_dark' => kirby()->site()->kolorNuance()->value(),
		'text' => kirby()->site()->title()->value()[0]
	],
```

Maybe it has troubles reading the fields of kirby-color-plugin https://github.com/TimOetting/kirby-color ?

**Comment by medienbaecker** [comment]
I figured it out.
You can't access the `site()` object in the config because it's not yet initialized. There is a [ready()](https://getkirby.com/docs/reference/system/options/ready) option though:

```php
<?php
// site/config/config.php
return [
  'ready' => function() {
    return [
      'medienbaecker.autofavicon.color' => kirby()->site()->color(),
      'medienbaecker.autofavicon.color_dark' => kirby()->site()->color()
    ];
  }
];
```
